# Generated by Django 5.1.5 on 2025-02-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_unique_together'),
        ('bookings', '0003_alter_booking_options_alter_booking_booking_type_and_more'),
    ]

    operations = [
    ]
