# Generated by Django 5.1.6 on 2025-02-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('start_time', 'booking_type')},
        ),
    ]
