# Generated by Django 5.1.7 on 2025-04-02 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Availability',
            new_name='MatchAvailability',
        ),
        migrations.AlterModelOptions(
            name='matchavailability',
            options={'verbose_name': 'Match Availability', 'verbose_name_plural': 'Match Availabilities'},
        ),
    ]
