# Generated by Django 5.1.6 on 2025-04-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingrequestmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequestmatch',
            name='requester_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
