# Generated by Django 5.1.7 on 2025-04-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_opponent_booking_opponent_result_and_more'),
        ('bookings', '0010_competition_competitionparticipant'),
    ]

    operations = [
    ]
