# Generated by Django 5.1.7 on 2025-05-02 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_merge_20250429_1245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10),
        ),
        migrations.CreateModel(
            name='CompetitionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('1v1', '1v1'), ('2v2', '2v2'), ('ffa', 'Free-for-All')], max_length=5)),
                ('round_number', models.PositiveIntegerField(blank=True, null=True)),
                ('match_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='bookings.competition')),
            ],
            options={
                'verbose_name': 'Competition Match',
                'verbose_name_plural': 'Competition Matches',
                'ordering': ['competition', 'round_number', 'match_datetime', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=10, null=True)),
                ('result_type', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw'), ('rank', 'Rank'), ('score', 'Score'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('result_value', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bookings.competitionmatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match Participant',
                'verbose_name_plural': 'Match Participants',
                'ordering': ['match', 'team', 'result_value'],
                'unique_together': {('match', 'user')},
            },
        ),
    ]
