# Generated by Django 5.1.7 on 2025-05-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_competition_status_competitionmatch_matchparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ranking_pool',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ranking_switch',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ranking_table_tennis',
            field=models.IntegerField(default=1500),
        ),
    ]
